### ISSUE TITLE
Remote Airplay device won't toggle in 1.5

### ISSUE THREAD

**Issue by benjdrummond** [dotson/iTunes-Airplay-Toggle#3]
In Catalina / Music / v1.5, the workflow successfully toggles computer playback, but it won't toggle Airplay on my Express. I get a notification of "Airplay Device Toggled," but without the second text line and nothing changes in the Music app. It worked beautifully with 1.4.

Thanks for your work on this. It's been an awesome tool!

**Comment by dotson** [comment]
Hi Ben, thanks for letting me know about this! A couple quick questions to try and help troubleshoot:

- Would you mind running this using the Alfred debugger tool and then copy/paste everything from the log window after the notification posts for me to take a look at? Screen shot provided below in case you're not sure what I'm referring to.

- Can you confirm if the workflow properly shows the list of your airplay devices in the Alfred window but just doesn't respond correctly when you select the device in Alfred list to toggle it?

- Can you confirm that when you manually select the device in the Music app everything works just as you'd expect? The issue is just the workflow and not Music/Catalina, correct?

- What is the exact type of airplay device you're trying to toggle? Sounds like it's an Airport Express that you've set up as an airplay device, correct? I doubt this is the issue, but good to know just in case.

Thanks again, really appreciate the info. I'm sure we can get this thing back up and running for you.

![Screen Shot 2019-11-15 at 9 04 02 PM](https://user-images.githubusercontent.com/4296385/68988402-a7ac0900-07eb-11ea-9572-f667b9dd4c11.png)

**Comment by benjdrummond** [comment]
Thanks for the quick reply!

Yes, the workflow shows the correct list of devices, just as it did in 1.4. And yes, the Airport Express works just fine in Music, where I can toggle it manually. The issue is simply that the workflow successfully toggles the computer output but has no effect on the Airport Express.

Debugger of when I choose the Airplay speaker from Alfred:
```
[21:20:45.553] Logging Started...
[21:20:48.279] iTunes Airplay Toggle[Hotkey] Processing complete
[21:20:48.281] iTunes Airplay Toggle[Hotkey] Passing output '' to Script Filter
[21:20:48.295] iTunes Airplay Toggle[Script Filter] Queuing argument ''
[21:20:48.673] iTunes Airplay Toggle[Script Filter] Script with argv '' finished
[21:20:48.675] iTunes Airplay Toggle[Script Filter] <?xml version="1.0"?>
<items>
	<item arg="" valid="no">
		<title>Available AirPlay Devices:</title>
		<subtitle>Select to toggle state.</subtitle>
		<icon>icon.png</icon>
	</item>
	<item arg="Computer">
		<title>Computer</title>
		<subtitle>Current State: On</subtitle>
		<icon>icon.png</icon>
	</item>
	<item arg="Airport Express">
		<title>Airport Express</title>
		<subtitle>Current State: Off</subtitle>
		<icon>icon.png</icon>
	</item>
</items>
[21:20:49.875] iTunes Airplay Toggle[Script Filter] Processing complete
[21:20:49.880] iTunes Airplay Toggle[Script Filter] Passing output 'Airport Express' to Run Script
[21:20:49.881] iTunes Airplay Toggle[Script Filter] Passing output 'Airport Express' to Run Script
[21:20:50.126] iTunes Airplay Toggle[Run Script] Processing complete
[21:20:50.132] iTunes Airplay Toggle[Run Script] Passing output '' to Post Notification
```

**Comment by dotson** [comment]
Thanks again, this is very useful. I have a couple Express models here and will try to reproduce this on my end over the weekend. I have a few ideas based on your debug text and will post a beta as soon as I can come up with potential solutions. Really appreciate your help so far.

**Comment by dotson** [comment]
Hi Ben,

When you have a minute, please give the new 1.5.1 version a try and let me know if it works for you. 

-Chris

**Comment by benjdrummond** [comment]
That fixed it. Thanks so much Chris!
